### PR TITLE
Updated filter to also include _init.cf in module documentation

### LINKED ISSUE #1: Content of _init.cf is ignored when generating docs

### PR DESCRIPTION
**Pull request by wouterdb**
fixes #1

### CODE REVIEW

**Review by bartv — CHANGES_REQUESTED** [review]
That was a recent fix because aws also matches aws-dc and some other examples as well. Hence the :: suffix. I did not notice the side effect that _init.cf entities were no longer loaded.

The current online docs are generated with this code https://docs.inmanta.com/community/latest/reference/modules/std.html and they contain everything from std itself.

**Comment by wouterdb** [comment]
I get the same problem with the std documentation, could you please verify?

I will also change the resolver to work on the actual module name, resolving the underlying issue

**Comment by wouterdb** [comment]
resolved in e57866caff6748b04e157f9542411224e9d8fe88

**Comment by wouterdb** [comment]
fixes #1

**Pull request closed without merging**
